### ISSUE TITLE
emoticons in post content result in four question marks

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-mediastream#1]
Eg https://www.instagram.com/p/CXBuU78INiL/ 

**_Original:_**
<img width="186" alt="Screenshot 2021-12-04 at 05 42 26" src="https://user-images.githubusercontent.com/1005986/144697279-05691d51-b223-45d0-9ba9-b208f75ed19a.png">

**_Result:_**
<img width="191" alt="Screenshot 2021-12-04 at 05 42 57" src="https://user-images.githubusercontent.com/1005986/144697302-856eb248-6b8a-4ad0-b678-39492747bcc0.png">

**Comment by patjnr** [comment]
For this work charset must be changed from utf8 to utf8mb4

SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_general_ci
  charset: utf8mb4
  collation: utf8mb4_general_ci

see https://github.com/silverstripe/silverstripe-framework/issues/8062

**Comment by micschk** [comment]
Adding to README
